apiVersion: v1
kind: Service
metadata:
  name: jvm-metrics-app
  labels:
    app: jvm-metrics-app
spec:
  type: ClusterIP
  selector:
    app: jvm-metrics-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
